# Generated by Django 4.2.1 on 2023-06-06 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('championnat', 'Championnat'), ('course_simple', 'Course Simple')], default='course_simple', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_images', verbose_name="Image d'illustration"),
        ),
        migrations.AlterField(
            model_name='pilote',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WSR.vehicule', verbose_name='Véhicule'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='position_arrivee',
            field=models.PositiveIntegerField(verbose_name="Position à l'arrivée"),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='position_depart',
            field=models.PositiveIntegerField(verbose_name='Position de départ'),
        ),
        migrations.AlterField(
            model_name='saison',
            name='annee',
            field=models.PositiveIntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='annee_fabrication',
            field=models.PositiveIntegerField(verbose_name='Année de fabrication'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(max_length=100, verbose_name='Modèle'),
        ),
    ]
