# Generated by Django 4.2.1 on 2023-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0002_alter_race_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('championship', 'Championship'), ('single_race', 'Single Race'), ('face_to_face', 'Face To Face'), ('overtaking', 'Overtaking')], default='single_race', max_length=100),
        ),
    ]
