# Generated by Django 4.2.1 on 2023-06-06 20:05
import random

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0002_course_date_course_type_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='score',
            field=models.IntegerField(default=random.randrange(500, 8000, 500)),
            preserve_default=False,
        ),
    ]
