# Generated by Django 4.2.2 on 2023-06-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0006_alter_race_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='race',
            name='participation_type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('participation', 'Participation')], default='participation', max_length=100),
        ),
        migrations.AlterField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('championship', 'Championship'), ('single_race', 'Single Race'), ('face_to_face', 'Face To Face'), ('overtaking', 'Overtaking'), ('against_time', 'Against Time'), ('elimination', 'Elimination'), ('endurance', 'Endurance'), ('touge', 'Touge')], default='single_race', max_length=100),
        ),
    ]
