# Generated by Django 4.2.2 on 2023-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0007_rename_name_race_location_race_participation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
