# Generated by Django 4.2.2 on 2023-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0008_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
