# Generated by Django 4.2.2 on 2023-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0009_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
