# Generated by Django 4.2.2 on 2023-06-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0010_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('championship', 'Championship'), ('single_race', 'Single Race'), ('face_to_face', 'Face To Face'), ('overtaking', 'Overtaking'), ('against_time', 'Against Time'), ('elimination', 'Elimination'), ('endurance', 'Endurance'), ('touge', 'Touge'), ('checkpoint', 'Checkpoint')], default='single_race', max_length=100),
        ),
    ]
