# Generated by Django 4.2.2 on 2023-06-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WSR', '0018_remove_racetype_font_awesome_icon_racetype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetype',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='racetypes', verbose_name='Vidéo de démonstration'),
        ),
    ]
